spring.application.name=backend

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/p21keystone
spring.datasource.username=p21user
spring.datasource.password=p21password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true